# Generated by Django 4.1 on 2024-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=20)),
                ("lastName", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=1)),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True, related_name="students", to="Lab6App.course"
                    ),
                ),
            ],
        ),
    ]
